import { promises as fs } from 'node:fs';
import paths from './paths.js';

/**
 * Writes out the flag files generated by concentrate
 *
 * This is needed so SiteHtmlHeadEntrySetDisplayer will use the compiled
 * LESS paths when rendering the page on the server.
 */
export async function writeCompiledFlag() {
  const ts = Math.floor(new Date().getTime() / 1000);
  await fs.writeFile(paths.compiledFlag, `${ts}`);
}
